

<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headTitle($this->translate('Safe Start API Reference'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/api-docs.css'); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/schema.js')->prependFile($this->basePath() . '/js/jquery.min.js'); ?>

</head>
<body>
    <?php echo $this->content; ?>
</body>
