<?php

$data = isset($this->answer) ? $this->answer : array('done' => false, 'error' => '500 api exception occurred');
$env = getenv('APP_ENV') ?: 'dev';
if ($env == 'dev') {
    if(isset($this->exception) && $this->exception instanceof Exception) {
        $data['trace'] = array(
            'exception' => get_class($this->exception),
            'file' => $this->exception->getFile() . ':'. $this->exception->getLine(),
            'message' => $this->exception->getMessage(),
            'stack' => $this->exception->getTraceAsString(),
        );
    }
}

echo json_encode(
    $response = array(
        'meta' => array(
            'status' => 500,
            'requestId' => isset($this->requestId) ? $this->requestId : '',
            'error' => true,
        ),
        'data' => $data
    )
);