<?php

$errorCode = $this->answer ? 0 : 2041;

echo json_encode(
    $response = array(
        'meta' => array(
            'status' =>  isset($this->statusCode) ? $this->statusCode : 0,
            'requestId' => isset($this->requestId) ? $this->requestId : '',
            'errorCode' => isset($this->errorCode) ? $this->errorCode : $errorCode,
        ),
        'data' => isset($this->answer) ? $this->answer : array('errorMessage' => 'no content')
    )
);
