<?php echo $this->doctype(); ?>

<?php $env = getenv('APP_ENV') ?: 'dev'; ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Safe Start App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon_16.ico'))
                ->prependStylesheet($this->basePath() . '/css/app.css'); ?>

        <script>
            var SafeStartApp = <?php echo json_encode($this->appConfig); ?>;
        </script>

        <?php
            switch($env) {
                case 'dev':
                    $microLoaderScript = 'development.js';
                    echo $this->headScript()->prependFile($this->basePath() . '/touch/microloader/' . $microLoaderScript);
                    break;
                case 'prod':
                    echo '<link href="/build/production/SafeStartApp/resources/css/app.css" media="screen" rel="stylesheet" type="text/css">';
                    echo '<link href="/build/production/SafeStartApp/resources/css/safe-start.css" media="screen" rel="stylesheet" type="text/css">';
                    echo '<script type="text/javascript" src="/build/production/SafeStartApp/app.js"></script>';
                    break;
                case 'testing':
                    $microLoaderScript = 'testing.js';
                    echo $this->headScript()->prependFile($this->basePath() . '/touch/microloader/' . $microLoaderScript);
                    break;
            }
        ?>
        <link href='http://fonts.googleapis.com/css?family=Archivo+Narrow' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
            window.qbaka || (function(a,c){a.__qbaka_eh=a.onerror;a.__qbaka_reports=[];a.onerror=function(){a.__qbaka_reports.push(arguments);if(a.__qbaka_eh)try{a.__qbaka_eh.apply(a,arguments)}catch(b){}};a.onerror.qbaka=1;a.qbaka={report:function(){a.__qbaka_reports.push([arguments, new Error()]);},customParams:{},set:function(a,b){qbaka.customParams[a]=b},exec:function(a){try{a()}catch(b){qbaka.reportException(b)}},reportException:function(){}};var b=c.createElement("script"),e=c.getElementsByTagName("script")[0],d=function(){e.parentNode.insertBefore(b,e)};b.type="text/javascript";b.async=!0;b.src="//cdn.qbaka.net/reporting.js";"[object Opera]"==a.opera?c.addEventListener("DOMContentLoaded",d):d();qbaka.key="f871c55d966a7e14acce89fbf2ea7f9e"})(window,document);qbaka.options={autoStacktrace:1,trackEvents:1};
        </script>
        <script type="text/javascript" src="https://www.google.com/jsapi"></script>
        <script type="text/javascript">
            google.load("maps", "3", {
                other_params: "sensor=false"
            });
        </script>

    </body>
</html>
