<?php echo $this->doctype(); ?>

<?php $env = getenv('APP_ENV') ?: 'dev'; ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Safe Start App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon_16.ico'))
                ->prependStylesheet($this->basePath() . '/css/app.css'); ?>

        <script>
            var SafeStartApp = <?php echo json_encode($this->appConfig); ?>;
        </script>

        <?php
            switch($env) {
                case 'dev':
                    $microLoaderScript = 'development.js';
                    echo $this->headScript()->prependFile($this->basePath() . '/touch/microloader/' . $microLoaderScript);
                    break;
                case 'prod':
                    echo '<link href="/build/SafeStartApp/production/resources/css/app.css" media="screen" rel="stylesheet" type="text/css">';
                    echo '<link href="/build/SafeStartApp/production/resources/css/safe-start.css" media="screen" rel="stylesheet" type="text/css">';
                    echo '<script type="text/javascript" src="/build/SafeStartApp/production/app.js"></script>';
                    break;
                case 'testing':
                    $microLoaderScript = 'testing.js';
                    echo $this->headScript()->prependFile($this->basePath() . '/touch/microloader/' . $microLoaderScript);
                    break;
            }
        ?>

    </head>
    <body>
        <?php echo $this->content; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
