<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
        body {
            background: #e5e9ec;
            font-size: 13.99px;
            color: #8c9297;
            font-family: 'Helvetica';
        }
    </style>
</head>

<body>
A fault was identified on <?php echo $this->plantId; ?> on <?php echo $this->creationDate; ?> and is due for closure in 24 hours.<br />
Please access the <a href="<?php echo $this->actionLink; ?>">Safe Start Database</a> to report on the status of the alert and if the required corrective action has been implemented.
</body>
</html>
